[package]
name = "predifi-contract"
version = "0.0.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
soroban-sdk = { workspace = true }
predifi-errors = { workspace = true }
access-control = { path = "../access-control" }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
